### PR TITLE
Initial import of Omega analysis toolchain.

### PR DESCRIPTION
**Pull request by scovetta**
This PR contains the basic Omega analysis toolchain, packaged as a Docker container and surrounding scripts.

### CODE REVIEW

**Comment by scovetta** [comment]
Thanks David! Yep, I've had a few conversations internally with GitHub for CodeQL, expecting a response shortly. I'll re-engage LF lawyers once we have clarity to make sure everything is kosher.

**Comment by scovetta** [comment]
I confirmed with GitHub and Microsoft that we're good to go here. We'll continue to point to the custom license terms in the analyzer readme and Dockerfile.

**Comment by brianbehlendorf** [comment]
Can I just get a concise description of what licenses are involved here? We don't have a clear policy beyond "things we build here at OpenSSF are released under the Apache license" and could probably use one when it comes to redistributing things as dependencies or convenience binaries.

**Comment by scovetta** [comment]
Of course -- the Docker container definition (the actual Dockerfile) and all of the related scripts, would be [Apache](https://github.com/ossf/alpha-omega/tree/scovetta/import-omega-analyzer/omega/analyzer#license).

When the Dockerfile builds, various tools are downloaded and installed into the image. For example, Graudit and Manalyze are available under the GPL, and CodeQL is available under a custom license.

I didn't want to make any implications that the binaries installed into the image were somehow being relicensed under Apache, and that the *use* of the analyzer, especially CodeQL, was still under that tool's original terms and conditions.

I've included this text in the readme, and called out each tool's license within the Dockerfile:

> License
> The Omega Analyzer scripts and all content that resides within this repository are licensed under the [Apache](https://github.com/ossf/alpha-omega/blob/scovetta/import-omega-analyzer/LICENSE) license. However, the [Dockerfile](https://github.com/ossf/alpha-omega/blob/scovetta/import-omega-analyzer/omega/analyzer/Dockerfile) downloads and installs other tools that are provided under separate licenses; for example:

> [CodeQL](https://codeql.github.com/) is provided under a [custom license](https://github.com/github/codeql-cli-binaries/blob/main/LICENSE.md), which you should understand before using this analyzer.
> [Radare2](https://rada.re/) is provided under the [LGPLv3 license](https://rada.re/r/license.html).
Please refer to the [Dockerfile](https://github.com/ossf/alpha-omega/blob/scovetta/import-omega-analyzer/omega/analyzer/Dockerfile) for more information about the varying licenses of the included tools and any restrictions that may apply to their use. In particular, ensure you understand the [restrictions for CodeQL](https://github.com/github/codeql-cli-binaries/blob/main/LICENSE.md).

**Comment by brianbehlendorf** [comment]
This seems reasonable - the only parts we are distributing are Apache License then. Carry on!

Brian

On August 19, 2022 9:41:49 AM GMT+09:00, Michael Scovetta ***@***.***> wrote:
>Of course -- the Docker container definition (the actual Dockerfile) and all of the related scripts, would be [Apache](https://github.com/ossf/alpha-omega/tree/scovetta/import-omega-analyzer/omega/analyzer#license).
>
>When the Dockerfile builds, various tools are downloaded and installed into the image. For example, Graudit and Manalyze are available under the GPL, and CodeQL is available under a custom license.
>
>I didn't want to make any implications that the binaries installed into the image were somehow being relicensed under Apache, and that the *use* of the analyzer, especially CodeQL, was still under that tool's original terms and conditions.
>
>I've included this text in the readme, and called out each tool's license within the Dockerfile:
>
>> License
>> The Omega Analyzer scripts and all content that resides within this repository are licensed under the [Apache](https://github.com/ossf/alpha-omega/blob/scovetta/import-omega-analyzer/LICENSE) license. However, the [Dockerfile](https://github.com/ossf/alpha-omega/blob/scovetta/import-omega-analyzer/omega/analyzer/Dockerfile) downloads and installs other tools that are provided under separate licenses; for example:
>
>> [CodeQL](https://codeql.github.com/) is provided under a [custom license](https://github.com/github/codeql-cli-binaries/blob/main/LICENSE.md), which you should understand before using this analyzer.
>> [Radare2](https://rada.re/) is provided under the [LGPLv3 license](https://rada.re/r/license.html).
>Please refer to the [Dockerfile](https://github.com/ossf/alpha-omega/blob/scovetta/import-omega-analyzer/omega/analyzer/Dockerfile) for more information about the varying licenses of the included tools and any restrictions that may apply to their use. In particular, ensure you understand the [restrictions for CodeQL](https://github.com/github/codeql-cli-binaries/blob/main/LICENSE.md).
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ossf/alpha-omega/pull/1#issuecomment-1220113759
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
