### PR TITLE
Add readme file for Alpha

### PR DESCRIPTION
**Pull request by fdegir**
The readme file for Alpha project is linked on the readme in the parent folder but readme file is missing. This PR creates basic readme file for Alpha.

### CODE REVIEW

**Review by scovetta — APPROVED** [review]

**Comment by scovetta** [comment]
Thanks for the contribution, @fdegir!

**Review by TateGunning — COMMENTED** [review]
Is this where the "signed of by TSG" theoretically goes? If so, what exactly is required? Responses welcomed. Thank you!

**Comment by scovetta** [comment]
@TateGunning Sorry, I'm not sure I understand what you mean, or what "TSG" is.

**Comment by TateGunning** [comment]
Yes, my response was out of bounds. I appreciate your response. After RE-reading, you would have to be a mind-reader to understand what it was I were trying to indicate lol. 

TSG was referring initials, and how our names represent the sign off feature. I studied after I sent my last response but still unsure how when or where or why to sign off so I threw my initials the response but should have added more color to the response. 

I believe a there is sign off option in settings but was curious if I could have signed off (by listing name and email) in the exact location as TSG response? Does a person sign off inside a response or or is it a settings function? I'll investigate in meantime. Best,

**Pull request merged**
