### PR TITLE
doc: add security-support-role for 2023

### PR DESCRIPTION
**Pull request by RafaelGSS**
cc: @mhdawson @rginn @PaulaPaul

### CODE REVIEW

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by RafaelGSS** [comment]
@scovetta can you merge it?

**Review by PaulaPaul — COMMENTED** [review]
Terrific- looking forward to the work ahead.

**Review by PaulaPaul — COMMENTED** [review]
Approved

**Review by scovetta — APPROVED** [review]

**Pull request merged**
